### ISSUE TITLE
Why correct_seqs_oh looks like that?

### ISSUE THREAD

**Issue by MateuszOtmianowski** [ckyeungac/deep-knowledge-tracing-plus#1]
Hello guys,

congratulations on your "Addressing Two Problems in Deep Knowledge Tracing via
Prediction-Consistent Regularization" paper. It is very interesting, and I enjoyed it very much. To get a deeper understanding of it I started analysing your code, and found a thing that is not clear to me. I would be very grateful if you could clarify it for me.
 
In OriginalInputProcessor class you have got a process_problems_and_corrects function. Let's assume that:

num_problems = 10
max_seq_length = 5

and one of the sequence pairs looks as following (same as in the comment in your script):

problem_seq = [1,3,2]
correct_seq = [1,0,1]

As I understand it, this function does the following:

1. Pad with -1 from the right.

problem_seqs_pad = [1,3,2,-1,-1]
problem_seqs_pad = [1,0,1,-1,-1]

2. Transform correct_seq.

[1,3,2,-1,-1] * [1,0,1,-1,-1] * [1,0,1,-1,-1] = [1,0,2,-1,-1] # problem_seqs_pad * correct_seq_pad * correct_seq_pad
correct_seqs_pad = [1,-1,2,-1,-1] # replaced 0s with -1s

3. One hot encode both variables:

problem_seqs_oh = array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
                                              [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
                                              [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
                                              [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
                                              [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

correct_seqs_oh = array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
                                            [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
                                            [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
                                            [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], 
                                            [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]) 

4. You than concatenate problem_seqs_oh and correct_seqs_oh to get the X (removing the last element of a sequence first).

What I don't understand here is why the correct_seq_oh looks this way? I could imagine that it could look like that:

correct_seqs_oh = [[1],
                                  [0],
                                  [1],
                                  [0],
                                  [0]]

so just the information whether the particular problem was solved correctly or not. It would make sense for me because we already have the information on the id of the problem in problem_seq, so one could argue that you don't need it once again in the correct_seqs_oh, but I feel that I might be missing something here.

Could you please explain why have you decided to make correct_seqs_oh look this way?

Best,
MO

**Comment by ckyeungac** [comment]
Thank for your question. I think this question is related to the neural network design. Let me explain by example.

Let's consider `num_problems=3`, `max_seq_length=3`, and using your proposed `correct_seq_oh`. Therefore, if `problem_seq = [1,3,2]` and `correct_seq = [1,0,1]`, we will obtain 
```
problem_seq_oh = [[1, 0, 0], [0, 0, 1], [0, 1, 0]]
correct_seq_oh  = [[1], [0], [1]]
# concatenate problem_seqs_oh and correct_seqs_oh
X = [[1, 0, 0, 1], [0, 0, 1, 0], [0, 1, 0, 1]]
```
This input will be passed to the neural network. To make it simple, let say we pass it to a hidden layer (without activation) with only 1 neuron, `h`. Thus, `h` can be calculated by 
`h = w_1 x_1 + w_2 x_2 + w_3 x_3 + w_4 x_4`.

 More clearly, replace the `x_i` to be `q_i` and `a_i` indicating the input source. Thus, 
`h = w_1 q_1 + w_2 q_2 + w_3 q_3 + w_4 a`

**By observing this equation, you can sense that no matter which question you are answering, the correct tag `a` will have the same effect `w_4` when computing the hidden unit `h`.** This might not be desired because answering question 1 correctly should have a different effect, compared to answering question 2 correctly.

Therefore, if we use the following
```
problem_seq_oh = [[1, 0, 0], [0, 0, 1], [0, 1, 0]]
correct_seq_oh = [[1, 0, 0], [0, 0, 0], [0, 1, 0]]
X = [[1, 0, 0, 1, 0, 0], [0, 0, 1, 0, 0, 0], [0, 1, 0, 0, 1, 0]]
```

The hidden unit `h` will be calculated as
`h = w_1 x_1 + w_2 x_2 + w_3 x_3 + w_4 a_1 + w_5 a_2 + w_6 a_3`.
Then, answering question 1 correctly will have a different effect, compared to answering question 2 correctly.

**Comment by MateuszOtmianowski** [comment]
It makes sense when you put it this way. Thank you for explanation!

**Comment by ckyeungac** [comment]
Glad that it helps.
